services:
  - type: web
    name: prisp-backend
    runtime: python
    repo: https://github.com/Ajumobi1/PRISP
    branch: main
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.init_db && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://prisp-frontend.onrender.com

  - type: web
    name: prisp-frontend
    runtime: node
    repo: https://github.com/Ajumobi1/PRISP
    branch: main
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -- --hostname 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: BACKEND_API_BASE_URL
        value: https://prisp-backend.onrender.com/api/v1
      - key: PORT
        value: "10000"
